const recordTypes = {
    SALE_DATE_CHANGE : 'SALE_DATE_CHANGE',
    PURCHASE_DATE_CHANGE : 'PURCHASE_DATE_CHANGE',

    SALE_RECORDS_START : 'SALE_RECORDS_START',
    SALE_RECORDS_SUCCESS : "SALE_RECORDS_SUCCESS",
    SALE_RECORDS_ERROR : 'SALE_RECORDS_ERROR',
    
    PURCHASE_RECORDS_START : 'PURCHASE_RECORDS_START',
    PURCHASE_RECORDS_SUCCESS : "PURCHASE_RECORDS_SUCCESS",
    PURCHASE_RECORDS_ERROR : 'PURCHASE_RECORDS_ERROR',
}

export default recordTypes;