const outletTypes  = {
    ALL_OUTLETS_START : 'ALL_OUTLETS_START',
    ALL_OUTLETS_SUCCESS : 'ALL_OUTLETS_SUCCESS',
    ALL_OUTLETS_ERROR : 'ALL_OUTLETS_ERROR',

    SELECT_OUTLET : 'SELECT_OUTLET',

    SINGLE_OUTLET_START : 'SINGLE_OUTLET_START',
    SINGLE_OUTLET_ERROR : 'SINGLE_OUTLET_ERROR',
    SINGLE_OUTLET_SUCCESS : 'SINGLE_OUTLET_SUCCESS',
}

export default outletTypes;