const productTypes = {
    ALL_PRODUCTS_START : 'ALL_PRODUCTS_START',
    ALL_PRODUCTS_SUCCESS : 'ALL_PRODUCTS_SUCCESS',
    ALL_PRODUCTS_ERROR : 'ALL_PRODUCTS_ERROR',

    CHANGE_PRODUCT_SEARCH : 'CHANGE_PRODUCT_SEARCH',

    ADD_PRODUCT_TO_CART : 'ADD_PRODUCT_TO_CART',
    REMOVE_PRODUCT_FROM_CART : 'REMOVE_PRODUCT_FROM_CART',
    UPDATE_PRODUCT_IN_CART : 'UPDATE_PRODUCT_IN_CART',

    CLEAR_PURCHASE_CART : 'CLEAR_PURCHASE_CART',

    ADD_PRCHASE_START : 'ADD_PURCHASE_START',
    ADD_PURCHASE_SUCCESS : 'ADD_PURCHASE_SUCCESS',
    ADD_PURCHASE_ERROR : 'ADD_PURCHASE_ERROR',

}

export default productTypes;