const itemTypes = {
    ITEMS_START : 'ITEMS_START',
    ITEMS_SUCCESS : 'ITEMS_SUCCESS',
    ITEMS_ERROR : 'ITEMS_ERROR',

    SEARCH_ITEM : 'SEARCH_ITEM',
    ADD_ITEM_TO_CART : 'ADD_ITEM_TO_CART',
    INCREASE_ITEM : 'INCREASE_ITEM',
    DECREASE_ITEM : 'DECREASE_ITEM',
    REMOVE_ITEM_FROM_CART : 'REMOVE_ITEM_FROM_CART',
    CLEAR_CART : 'CLEAR_CART',

    CART_TOGGLE : 'CART_TOGGLE',

    ADD_SALE_START : 'ADD_SALE_START',
    ADD_SALE_SUCCESS : 'ADD_SALE_SUCCESS',
    ADD_SALE_ERROR : 'ADD_SALE_ERROR',
}


export default itemTypes;